create table if not exists customers (
  customer_id integer generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  gender text not null,
  birthdate date not null,
  created_at timestamptz not null,
  city text,
  state text,
  zip_code text,
  customer_segment text,
  loyalty_tier text,
  is_active boolean not null default true
);

create table if not exists products (
  product_id integer generated by default as identity primary key,
  sku text not null unique,
  product_name text not null,
  category text not null,
  price numeric(12,2) not null,
  cost numeric(12,2) not null,
  is_active boolean not null default true
);

create table if not exists orders (
  order_id integer generated by default as identity primary key,
  customer_id integer not null references customers(customer_id),
  order_datetime timestamptz not null,
  billing_zip text,
  shipping_zip text,
  shipping_state text,
  payment_method text not null,
  device_type text not null,
  ip_country text not null,
  promo_used boolean not null default false,
  promo_code text,
  order_subtotal numeric(12,2) not null,
  shipping_fee numeric(12,2) not null,
  tax_amount numeric(12,2) not null,
  order_total numeric(12,2) not null,
  risk_score numeric(5,2) not null,
  is_fraud boolean not null default false
);

create table if not exists shipments (
  shipment_id integer generated by default as identity primary key,
  order_id integer not null unique references orders(order_id),
  ship_datetime timestamptz not null,
  carrier text not null,
  shipping_method text not null,
  distance_band text not null,
  promised_days integer not null,
  actual_days integer not null,
  late_delivery boolean not null default false
);

create table if not exists order_items (
  order_item_id integer generated by default as identity primary key,
  order_id integer not null references orders(order_id),
  product_id integer not null references products(product_id),
  quantity integer not null,
  unit_price numeric(12,2) not null,
  line_total numeric(12,2) not null
);

create table if not exists product_reviews (
  review_id integer generated by default as identity primary key,
  customer_id integer not null references customers(customer_id),
  product_id integer not null references products(product_id),
  rating integer not null check (rating between 1 and 5),
  review_datetime timestamptz not null,
  review_text text,
  unique (customer_id, product_id)
);

create table if not exists delivery_scores (
  order_id integer primary key references orders(order_id),
  late_delivery_probability numeric(5,4) not null,
  scored_at timestamptz not null,
  score_source text not null,
  model_version text not null
);

create index if not exists idx_orders_customer_id on orders(customer_id);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_shipments_order_id on shipments(order_id);
create index if not exists idx_delivery_scores_probability on delivery_scores(late_delivery_probability desc);
